### PR TITLE
change after_destroy callback to before_destroy so that the source is…

### PR DESCRIPTION
**Pull request by oorion**
… still available when determining which data to save for later presentation in an audit log

### CODE REVIEW

**Review by grosser — CHANGES_REQUESTED** [review]
can you add a test case that fails without this change ?

**Comment by grosser** [comment]
... I need to fix CI first 😞

**Comment by oorion** [comment]
This PR might not be necessary actually.  Will let you know.

**Comment by grosser** [comment]
FYI master has CI now so ca rebase

**Pull request closed without merging**
