### PR TITLE
Add inverse_of between AttributeChange and Event

### PR DESCRIPTION
**Pull request by pschambacher**
@grosser this fixes https://github.com/rails/rails/issues/10983

### CODE REVIEW

**Comment by grosser** [comment]
:+1: any way to add a test for it ?

**Comment by pschambacher** [comment]
Well there's one in Classic :smile:

**Comment by grosser** [comment]
good enough I guess ... if you can reproduce having a test here would be nice :)

**Comment by grosser** [comment]
can you rebase too ?

**Comment by pschambacher** [comment]
will do

**Comment by pschambacher** [comment]
Rebase is done.
Regarding the repro of the issue, no luck reproducing it... Anything I try to write is green on master as well so it's not testing anything.

**Comment by grosser** [comment]
v0.5.9 is out!

**Pull request merged**
